Semplice e veloce quanto incompleta verifica dell'affermazione in https://wiki.c2sm.ethz.ch/pub/COSMO/ProjPOMPATask1/report_hp2c_profiling.pdf (purtroppo, recentemente diventato un broken link):

> Initial benchmarking of COSMO (COSMO 4.10 RAPS benchmark) tends to indicate that memory bandwidth is a key limitation. Table 1 lists timings of the overall model (at 7km resolution) – split into dynamics and physics parts. When run on identical numbers of cores, but on different numbers of nodes or sockets (1 or 2 per node), the use  of more nodes/sockets with fewer cores per node/socket allows the cores a higher proportion of the node’s memory bandwidth. Since reducing the number of cores reduces  the execution times noticeably, we conclude that memory bandwidth is one of possibly several bottlenecks. In other words, many (but not all) of the computational routines suffer from low computational intensity (floating point operations per memory access) and low cache reuse. Note also that these results are a strong function of the ratio of node peak performance to memory bandwidth of the specific architecture.

La cosa si può verificare andando a prendere dei job con medesima configurazione tranne che per l'uso di un diverso numero di nodi e core per nodo, ma che hanno lo stesso numero di processi e guardando il tempo di esecuzione.

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("fixed_area_results.csv")

Prendiamo la risoluzione massima e doppia precisione, che sono quelle che hanno tempi più lunghi e quindi in cui si apprezzano maggiormente le variazioni di tempo di esecuzione. Uso `subdomain_ratio = 1` perchè è quello generalmente con più combinazioni presenti.

In [3]:
df.query("grid_step==20 and subdomain_ratio == 1 and single_precision == 0").groupby("n_procs")["n_procs"].count()

n_procs
196     1
256     1
324     1
400     2
484     1
576     5
600     6
676     1
784     3
812     4
900     4
930     2
1024    1
1056    6
1156    1
1190    2
1296    2
1332    2
1368    4
1560    4
1600    1
1764    1
1980    2
Name: n_procs, dtype: int64

Prendo in considerazione i job con numero di processi pari a 576, 600 e 1056, che hanno un po' di combinazioni diverse.

In [4]:
df.query("grid_step==20 and subdomain_ratio == 1 and single_precision == 1 and n_procs == 576")[["n_nodes", "n_cores", "time2"]].sort_values(["n_nodes", "n_cores"])

n_nodes  n_cores  time2
447        16       36  31.61
567        18       32  28.46
935        24       24  25.48
1465       32       18  24.03
1757       36       16  23.91

In [5]:
df.query("grid_step==20 and subdomain_ratio == 1 and single_precision == 1 and n_procs == 600")[["n_nodes", "n_cores", "time2"]].sort_values(["n_nodes", "n_cores"])

n_nodes  n_cores  time2
685        20       30  26.79
687        20       30  27.56
1011       25       24  25.40
1013       25       24  24.37
1335       30       20  23.58
1337       30       20  23.32

In [6]:
df.query("grid_step==20 and subdomain_ratio == 1 and single_precision == 1 and n_procs == 1056")[["n_nodes", "n_cores", "time2"]].sort_values(["n_nodes", "n_cores"])

n_nodes  n_cores  time2
1577       33       32  18.88
1579       33       32  18.14
2265       44       24  16.56
2267       44       24  15.79
2519       48       22  15.73
2521       48       22  15.40

Si può notare come, a parità di processi, distribuendo i core su più nodi si abbiano tempi di esecuzione più bassi.